<?php

/**
 * Sample Job Listings Data
 *
 * This array contains sample job data for testing and demonstration purposes.
 * In a real application, this data would typically come from a database.
 */

$sampleJobs = [
    [
        'user_id' => 1, // Assuming user ID 1 is an HR/Admin who posted this
        'title' => 'Senior Frontend Developer',
        'company' => 'Innovate Solutions',
        'logo' => 'https://ui-avatars.com/api/?name=IS&background=0D8ABC&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$110,000 - $140,000',
        'description' => 'Seeking an experienced Frontend Developer to lead our UI/UX initiatives. Must be proficient in React, TypeScript, and modern CSS frameworks. Responsibilities include developing new user-facing features, building reusable code and libraries, and ensuring the technical feasibility of UI/UX designs.',
        'skills' => json_encode(['React', 'TypeScript', 'CSS', 'HTML', 'JavaScript', 'UI/UX Design', 'Git']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-3 days')),
        'expires_at' => date('Y-m-d', strtotime('+27 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2, // Assuming user ID 2 is an HR/Admin
        'title' => 'Backend Engineer (Python/Django)',
        'company' => 'Data Insights Inc.',
        'logo' => 'https://ui-avatars.com/api/?name=DI&background=4C1D95&color=fff&size=128',
        'location' => 'New York',
        'job_type' => 'Full-time',
        'salary' => '$100,000 - $130,000',
        'description' => 'Join our backend team to build scalable APIs and data processing pipelines using Python and Django. Experience with PostgreSQL and AWS is a plus. You will work closely with data scientists and frontend developers.',
        'skills' => json_encode(['Python', 'Django', 'PostgreSQL', 'API Development', 'AWS', 'REST', 'Docker']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
        'expires_at' => date('Y-m-d', strtotime('+25 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Cloud DevOps Engineer',
        'company' => 'CloudSystems Ltd.',
        'logo' => 'https://ui-avatars.com/api/?name=CS&background=065F46&color=fff&size=128',
        'location' => 'San Francisco',
        'job_type' => 'Full-time',
        'salary' => '$120,000 - $150,000',
        'description' => 'Manage and automate our cloud infrastructure on AWS. Strong experience with Terraform, Kubernetes, and CI/CD pipelines required. Implement monitoring and alerting solutions.',
        'skills' => json_encode(['AWS', 'Terraform', 'Kubernetes', 'Docker', 'CI/CD', 'Linux', 'Ansible']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'expires_at' => date('Y-m-d', strtotime('+29 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3, // Assuming user ID 3 is an HR/Admin
        'title' => 'Marketing Manager',
        'company' => 'Growth Hub',
        'logo' => 'https://ui-avatars.com/api/?name=GH&background=9D174D&color=fff&size=128',
        'location' => 'London',
        'job_type' => 'Full-time',
        'salary' => '£50,000 - £65,000',
        'description' => 'Lead our marketing campaigns across digital channels. Proven experience in SEO, SEM, and content marketing needed. Develop and execute marketing strategies to drive growth.',
        'skills' => json_encode(['Digital Marketing', 'SEO', 'SEM', 'Content Marketing', 'Social Media', 'Analytics', 'Email Marketing']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-10 days')),
        'expires_at' => date('Y-m-d', strtotime('+20 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Data Scientist',
        'company' => 'AnalyticsPro',
        'logo' => 'https://ui-avatars.com/api/?name=AP&background=1E3A8A&color=fff&size=128',
        'location' => 'Berlin',
        'job_type' => 'Full-time',
        'salary' => '€70,000 - €90,000',
        'description' => 'Develop machine learning models to extract insights from large datasets. Proficiency in Python, R, SQL, and ML frameworks required. Communicate findings to stakeholders.',
        'skills' => json_encode(['Python', 'R', 'SQL', 'Machine Learning', 'Data Analysis', 'Statistics', 'TensorFlow']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-7 days')),
        'expires_at' => date('Y-m-d', strtotime('+23 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'UI/UX Designer',
        'company' => 'Creative Minds',
        'logo' => 'https://ui-avatars.com/api/?name=CM&background=7C2D12&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Contract',
        'salary' => '$60 - $80 / hour',
        'description' => 'Design intuitive and visually appealing interfaces for web and mobile applications. Portfolio showcasing user-centered design required. Collaborate with product managers and developers.',
        'skills' => json_encode(['UI Design', 'UX Design', 'Figma', 'Sketch', 'Prototyping', 'User Research', 'Wireframing']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-2 days')),
        'expires_at' => date('Y-m-d', strtotime('+18 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Software Engineer (Java)',
        'company' => 'Enterprise Tech',
        'logo' => 'https://ui-avatars.com/api/?name=ET&background=5B21B6&color=fff&size=128',
        'location' => 'Austin',
        'job_type' => 'Full-time',
        'salary' => '$95,000 - $125,000',
        'description' => 'Develop and maintain enterprise-level applications using Java and Spring Boot. Experience with microservices and databases is essential. Write clean, maintainable code.',
        'skills' => json_encode(['Java', 'Spring Boot', 'Microservices', 'SQL', 'Hibernate', 'REST API', 'Maven']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-15 days')),
        'expires_at' => date('Y-m-d', strtotime('+15 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Product Manager',
        'company' => 'NextGen Apps',
        'logo' => 'https://ui-avatars.com/api/?name=NA&background=1E40AF&color=fff&size=128',
        'location' => 'Seattle',
        'job_type' => 'Full-time',
        'salary' => '$130,000 - $160,000',
        'description' => 'Define product strategy, roadmap, and feature requirements for our mobile applications. Strong technical background preferred. Work with cross-functional teams.',
        'skills' => json_encode(['Product Management', 'Agile', 'Roadmapping', 'User Stories', 'Market Research', 'Mobile Apps', 'JIRA']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-8 days')),
        'expires_at' => date('Y-m-d', strtotime('+22 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Junior Web Developer',
        'company' => 'WebStart Co.',
        'logo' => 'https://ui-avatars.com/api/?name=WS&background=0D8ABC&color=fff&size=128',
        'location' => 'Chicago',
        'job_type' => 'Internship',
        'salary' => '$20 - $25 / hour',
        'description' => 'Assist senior developers in building and maintaining websites. Basic knowledge of HTML, CSS, and JavaScript required. Eager to learn!',
        'skills' => json_encode(['HTML', 'CSS', 'JavaScript', 'Git']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-4 days')),
        'expires_at' => date('Y-m-d', strtotime('+26 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'HR Specialist',
        'company' => 'People First Inc.',
        'logo' => 'https://ui-avatars.com/api/?name=PF&background=4C1D95&color=fff&size=128',
        'location' => 'Boston',
        'job_type' => 'Full-time',
        'salary' => '$60,000 - $75,000',
        'description' => 'Manage recruitment, onboarding, and employee relations. Experience with HRIS systems and employment law is necessary. Support HR initiatives.',
        'skills' => json_encode(['Recruitment', 'Onboarding', 'Employee Relations', 'HRIS', 'Compliance', 'Communication']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-12 days')),
        'expires_at' => date('Y-m-d', strtotime('+18 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Mobile Developer (iOS)',
        'company' => 'AppCrafters',
        'logo' => 'https://ui-avatars.com/api/?name=AC&background=065F46&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$105,000 - $135,000',
        'description' => 'Develop native iOS applications using Swift and SwiftUI. Experience with Core Data and REST APIs needed. Collaborate with designers and backend engineers.',
        'skills' => json_encode(['iOS Development', 'Swift', 'SwiftUI', 'Core Data', 'REST API', 'Xcode', 'Git']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-6 days')),
        'expires_at' => date('Y-m-d', strtotime('+24 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Full Stack Engineer (Node.js/React)',
        'company' => 'Synergy Systems',
        'logo' => 'https://ui-avatars.com/api/?name=SS&background=9D174D&color=fff&size=128',
        'location' => 'Denver',
        'job_type' => 'Full-time',
        'salary' => '$115,000 - $145,000',
        'description' => 'Build end-to-end web applications using Node.js for the backend and React for the frontend. Experience with MongoDB and GraphQL is a plus.',
        'skills' => json_encode(['Node.js', 'React', 'JavaScript', 'MongoDB', 'GraphQL', 'Full Stack Development', 'Express.js']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-9 days')),
        'expires_at' => date('Y-m-d', strtotime('+21 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Cyber Security Analyst',
        'company' => 'SecureNet',
        'logo' => 'https://ui-avatars.com/api/?name=SN&background=1E3A8A&color=fff&size=128',
        'location' => 'Washington D.C.',
        'job_type' => 'Full-time',
        'salary' => '$90,000 - $120,000',
        'description' => 'Monitor security events, investigate incidents, and implement security controls. Certifications like CISSP or CompTIA Security+ preferred.',
        'skills' => json_encode(['Cyber Security', 'Incident Response', 'SIEM', 'Network Security', 'Vulnerability Assessment', 'Firewalls', 'Penetration Testing']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-11 days')),
        'expires_at' => date('Y-m-d', strtotime('+19 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Technical Writer',
        'company' => 'DocuTech',
        'logo' => 'https://ui-avatars.com/api/?name=DT&background=7C2D12&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Part-time',
        'salary' => '$35 - $50 / hour',
        'description' => 'Create clear and concise technical documentation, user guides, and API references for software products. Work with engineers and product managers.',
        'skills' => json_encode(['Technical Writing', 'Documentation', 'API Documentation', 'Markdown', 'Editing', 'Confluence']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
        'expires_at' => date('Y-m-d', strtotime('+25 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Database Administrator (MySQL)',
        'company' => 'Reliable Data',
        'logo' => 'https://ui-avatars.com/api/?name=RD&background=5B21B6&color=fff&size=128',
        'location' => 'Dallas',
        'job_type' => 'Full-time',
        'salary' => '$85,000 - $110,000',
        'description' => 'Manage, optimize, and secure our MySQL database infrastructure. Experience with performance tuning and backups required. Ensure high availability.',
        'skills' => json_encode(['Database Administration', 'MySQL', 'Performance Tuning', 'Backup & Recovery', 'SQL', 'Linux', 'Shell Scripting']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-14 days')),
        'expires_at' => date('Y-m-d', strtotime('+16 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Content Strategist',
        'company' => 'Engage Media',
        'logo' => 'https://ui-avatars.com/api/?name=EM&background=1E40AF&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $90,000',
        'description' => 'Develop content strategies aligned with marketing goals. Oversee content creation, distribution, and performance analysis. Strong writing and SEO skills needed.',
        'skills' => json_encode(['Content Strategy', 'Content Marketing', 'SEO', 'Writing', 'Editing', 'Analytics', 'Social Media']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-18 days')),
        'expires_at' => date('Y-m-d', strtotime('+12 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'QA Engineer (Automation)',
        'company' => 'QualityFirst Software',
        'logo' => 'https://ui-avatars.com/api/?name=QF&background=0D8ABC&color=fff&size=128',
        'location' => 'Toronto',
        'job_type' => 'Full-time',
        'salary' => '$80,000 - $105,000',
        'description' => 'Design and implement automated test suites for web applications. Experience with Selenium, Cypress, or similar tools required. Identify and report bugs.',
        'skills' => json_encode(['QA Automation', 'Selenium', 'Cypress', 'JavaScript', 'Testing Frameworks', 'Bug Tracking', 'Agile']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-20 days')),
        'expires_at' => date('Y-m-d', strtotime('+10 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Network Engineer',
        'company' => 'Connect Solutions',
        'logo' => 'https://ui-avatars.com/api/?name=CS&background=4C1D95&color=fff&size=128',
        'location' => 'Atlanta',
        'job_type' => 'Full-time',
        'salary' => '$90,000 - $115,000',
        'description' => 'Design, implement, and maintain network infrastructure. Experience with Cisco routers/switches, firewalls, and VPNs required. CCNA/CCNP preferred.',
        'skills' => json_encode(['Network Engineering', 'Cisco IOS', 'Routing', 'Switching', 'Firewalls', 'VPN', 'TCP/IP']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-22 days')),
        'expires_at' => date('Y-m-d', strtotime('+8 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Business Analyst',
        'company' => 'Strategic Insights',
        'logo' => 'https://ui-avatars.com/api/?name=SI&background=065F46&color=fff&size=128',
        'location' => 'Chicago',
        'job_type' => 'Full-time',
        'salary' => '$75,000 - $95,000',
        'description' => 'Gather and analyze business requirements, document processes, and facilitate communication between stakeholders and technical teams. Strong analytical skills needed.',
        'skills' => json_encode(['Business Analysis', 'Requirements Gathering', 'Process Modeling', 'SQL', 'Data Analysis', 'Communication', 'Agile']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-25 days')),
        'expires_at' => date('Y-m-d', strtotime('+5 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Mobile Developer (Android)',
        'company' => 'DroidWorks',
        'logo' => 'https://ui-avatars.com/api/?name=DW&background=9D174D&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$100,000 - $130,000',
        'description' => 'Develop native Android applications using Kotlin and Jetpack Compose. Experience with MVVM architecture and REST APIs required.',
        'skills' => json_encode(['Android Development', 'Kotlin', 'Jetpack Compose', 'MVVM', 'REST API', 'Android Studio', 'Git']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-3 days')),
        'expires_at' => date('Y-m-d', strtotime('+27 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Systems Administrator',
        'company' => 'InfraServe',
        'logo' => 'https://ui-avatars.com/api/?name=IS&background=1E3A8A&color=fff&size=128',
        'location' => 'Phoenix',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $90,000',
        'description' => 'Manage Windows and Linux server environments, including patching, monitoring, and troubleshooting. Experience with Active Directory and virtualization.',
        'skills' => json_encode(['System Administration', 'Windows Server', 'Linux', 'Active Directory', 'VMware', 'Networking', 'Scripting']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-28 days')),
        'expires_at' => date('Y-m-d', strtotime('+2 days')),
        'is_active' => 0, // Example of an inactive/expired job
    ],
    [
        'user_id' => 3,
        'title' => 'Graphic Designer',
        'company' => 'Visual Concepts',
        'logo' => 'https://ui-avatars.com/api/?name=VC&background=7C2D12&color=fff&size=128',
        'location' => 'Los Angeles',
        'job_type' => 'Contract',
        'salary' => '$50 - $70 / hour',
        'description' => 'Create compelling visual assets for marketing campaigns, websites, and social media. Proficiency in Adobe Creative Suite required. Portfolio needed.',
        'skills' => json_encode(['Graphic Design', 'Adobe Photoshop', 'Adobe Illustrator', 'Branding', 'Typography', 'Layout Design']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'expires_at' => date('Y-m-d', strtotime('+29 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Sales Development Representative',
        'company' => 'LeadGen Pro',
        'logo' => 'https://ui-avatars.com/api/?name=LG&background=5B21B6&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$50,000 - $65,000 + Commission',
        'description' => 'Generate qualified leads for the sales team through outbound prospecting (email, calls, social). Excellent communication skills required.',
        'skills' => json_encode(['Sales Development', 'Lead Generation', 'Prospecting', 'Cold Calling', 'Email Outreach', 'CRM', 'Communication']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-10 days')),
        'expires_at' => date('Y-m-d', strtotime('+20 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Machine Learning Engineer',
        'company' => 'AI Innovations',
        'logo' => 'https://ui-avatars.com/api/?name=AI&background=1E40AF&color=fff&size=128',
        'location' => 'Palo Alto',
        'job_type' => 'Full-time',
        'salary' => '$140,000 - $180,000',
        'description' => 'Design, build, and deploy machine learning models into production systems. Strong background in software engineering and ML frameworks (TensorFlow, PyTorch).',
        'skills' => json_encode(['Machine Learning', 'Python', 'TensorFlow', 'PyTorch', 'Software Engineering', 'Cloud Platforms', 'MLOps']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-15 days')),
        'expires_at' => date('Y-m-d', strtotime('+15 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Customer Success Manager',
        'company' => 'ClientFirst SaaS',
        'logo' => 'https://ui-avatars.com/api/?name=CF&background=0D8ABC&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$75,000 - $95,000',
        'description' => 'Build relationships with key clients, ensure they achieve their desired outcomes using our software, and drive renewals and upsells. Strong communication skills.',
        'skills' => json_encode(['Customer Success', 'Account Management', 'SaaS', 'Relationship Building', 'Communication', 'CRM']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
        'expires_at' => date('Y-m-d', strtotime('+25 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'IT Support Specialist',
        'company' => 'HelpDesk Heroes',
        'logo' => 'https://ui-avatars.com/api/?name=HH&background=4C1D95&color=fff&size=128',
        'location' => 'Miami',
        'job_type' => 'Full-time',
        'salary' => '$50,000 - $65,000',
        'description' => 'Provide technical support to end-users for hardware, software, and network issues. Troubleshoot problems and escalate when necessary. Excellent customer service skills.',
        'skills' => json_encode(['IT Support', 'Troubleshooting', 'Windows', 'MacOS', 'Active Directory', 'Networking Basics', 'Customer Service']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-8 days')),
        'expires_at' => date('Y-m-d', strtotime('+22 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Blockchain Developer',
        'company' => 'Decentralized Future',
        'logo' => 'https://ui-avatars.com/api/?name=DF&background=065F46&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$120,000 - $160,000',
        'description' => 'Develop smart contracts and decentralized applications (dApps) on Ethereum or other blockchain platforms. Experience with Solidity and Web3.js/Ethers.js.',
        'skills' => json_encode(['Blockchain', 'Solidity', 'Ethereum', 'Smart Contracts', 'Web3.js', 'Cryptography', 'Node.js']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-12 days')),
        'expires_at' => date('Y-m-d', strtotime('+18 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Social Media Manager',
        'company' => 'Viral Buzz Agency',
        'logo' => 'https://ui-avatars.com/api/?name=VB&background=9D174D&color=fff&size=128',
        'location' => 'New York',
        'job_type' => 'Full-time',
        'salary' => '$60,000 - $75,000',
        'description' => 'Manage social media presence across platforms (Facebook, Instagram, Twitter, LinkedIn). Create engaging content, run campaigns, and analyze performance.',
        'skills' => json_encode(['Social Media Marketing', 'Content Creation', 'Community Management', 'Analytics', 'Copywriting', 'Hootsuite']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-2 days')),
        'expires_at' => date('Y-m-d', strtotime('+28 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Project Manager (Software)',
        'company' => 'AgileFlow Solutions',
        'logo' => 'https://ui-avatars.com/api/?name=AF&background=1E3A8A&color=fff&size=128',
        'location' => 'San Jose',
        'job_type' => 'Full-time',
        'salary' => '$100,000 - $130,000',
        'description' => 'Manage software development projects using Agile methodologies. Coordinate sprints, manage backlogs, and ensure timely delivery. PMP or Scrum Master certification is a plus.',
        'skills' => json_encode(['Project Management', 'Agile', 'Scrum', 'JIRA', 'Software Development Lifecycle', 'Risk Management', 'Communication']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-18 days')),
        'expires_at' => date('Y-m-d', strtotime('+12 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Data Engineer',
        'company' => 'Pipeline Pros',
        'logo' => 'https://ui-avatars.com/api/?name=PP&background=7C2D12&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$110,000 - $140,000',
        'description' => 'Build and maintain scalable data pipelines for ingestion, processing, and storage. Experience with ETL tools, Spark, Kafka, and cloud data warehouses (Snowflake, BigQuery).',
        'skills' => json_encode(['Data Engineering', 'ETL', 'Python', 'SQL', 'Apache Spark', 'Kafka', 'AWS', 'Airflow']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-6 days')),
        'expires_at' => date('Y-m-d', strtotime('+24 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Financial Analyst',
        'company' => 'Capital Growth Partners',
        'logo' => 'https://ui-avatars.com/api/?name=CG&background=5B21B6&color=fff&size=128',
        'location' => 'New York',
        'job_type' => 'Full-time',
        'salary' => '$80,000 - $100,000',
        'description' => 'Perform financial forecasting, reporting, and operational metrics tracking. Analyze financial data and create financial models for decision support. Strong Excel skills required.',
        'skills' => json_encode(['Financial Analysis', 'Financial Modeling', 'Excel', 'Forecasting', 'Budgeting', 'Accounting Principles', 'SQL']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-20 days')),
        'expires_at' => date('Y-m-d', strtotime('+10 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'UX Researcher',
        'company' => 'User Insights Lab',
        'logo' => 'https://ui-avatars.com/api/?name=UI&background=1E40AF&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Contract',
        'salary' => '$65 - $85 / hour',
        'description' => 'Conduct user research studies (interviews, surveys, usability testing) to inform product design decisions. Synthesize findings and present actionable insights.',
        'skills' => json_encode(['UX Research', 'User Interviews', 'Usability Testing', 'Survey Design', 'Qualitative Analysis', 'Quantitative Analysis', 'Persona Development']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-4 days')),
        'expires_at' => date('Y-m-d', strtotime('+26 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Embedded Systems Engineer',
        'company' => 'Core Hardware Inc.',
        'logo' => 'https://ui-avatars.com/api/?name=CH&background=0D8ABC&color=fff&size=128',
        'location' => 'San Diego',
        'job_type' => 'Full-time',
        'salary' => '$100,000 - $130,000',
        'description' => 'Design, develop, and test firmware for embedded systems. Proficiency in C/C++ and experience with microcontrollers (ARM, PIC) required. RTOS experience is a plus.',
        'skills' => json_encode(['Embedded Systems', 'C', 'C++', 'Microcontrollers', 'Firmware', 'RTOS', 'Hardware Debugging']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-22 days')),
        'expires_at' => date('Y-m-d', strtotime('+8 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Recruiter (Technical)',
        'company' => 'Talent Finders',
        'logo' => 'https://ui-avatars.com/api/?name=TF&background=4C1D95&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $90,000 + Bonus',
        'description' => 'Source, screen, and recruit technical candidates (engineers, developers, data scientists). Manage the full recruitment lifecycle. Experience with ATS systems.',
        'skills' => json_encode(['Technical Recruiting', 'Sourcing', 'Screening', 'Interviewing', 'ATS', 'LinkedIn Recruiter', 'Negotiation']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-9 days')),
        'expires_at' => date('Y-m-d', strtotime('+21 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Cloud Architect',
        'company' => 'SkyHigh Solutions',
        'logo' => 'https://ui-avatars.com/api/?name=SH&background=065F46&color=fff&size=128',
        'location' => 'Austin',
        'job_type' => 'Full-time',
        'salary' => '$150,000 - $190,000',
        'description' => 'Design and implement scalable, secure, and cost-effective cloud solutions on AWS, Azure, or GCP. Provide technical leadership and guidance. Cloud certifications required.',
        'skills' => json_encode(['Cloud Architecture', 'AWS', 'Azure', 'GCP', 'Solution Design', 'Infrastructure as Code', 'Security', 'Networking']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'expires_at' => date('Y-m-d', strtotime('+29 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Game Developer (Unity)',
        'company' => 'PixelPlay Studios',
        'logo' => 'https://ui-avatars.com/api/?name=PS&background=9D174D&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$80,000 - $110,000',
        'description' => 'Develop games using the Unity engine and C#. Implement gameplay mechanics, UI, and optimize performance for various platforms (PC, mobile).',
        'skills' => json_encode(['Game Development', 'Unity', 'C#', 'Gameplay Programming', 'UI Development', 'Optimization', 'Version Control']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-11 days')),
        'expires_at' => date('Y-m-d', strtotime('+19 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Operations Manager',
        'company' => 'Efficiency Experts',
        'logo' => 'https://ui-avatars.com/api/?name=EE&background=1E3A8A&color=fff&size=128',
        'location' => 'Denver',
        'job_type' => 'Full-time',
        'salary' => '$90,000 - $120,000',
        'description' => 'Oversee daily operations, improve processes, manage budgets, and lead operational teams. Strong leadership and problem-solving skills required.',
        'skills' => json_encode(['Operations Management', 'Process Improvement', 'Budgeting', 'Leadership', 'Logistics', 'Supply Chain', 'Problem Solving']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-25 days')),
        'expires_at' => date('Y-m-d', strtotime('+5 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'SEO Specialist',
        'company' => 'RankUp Digital',
        'logo' => 'https://ui-avatars.com/api/?name=RU&background=7C2D12&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$65,000 - $85,000',
        'description' => 'Develop and implement SEO strategies to improve organic search rankings. Conduct keyword research, on-page optimization, link building, and technical SEO audits.',
        'skills' => json_encode(['SEO', 'Keyword Research', 'On-Page Optimization', 'Link Building', 'Technical SEO', 'Google Analytics', 'SEM']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-7 days')),
        'expires_at' => date('Y-m-d', strtotime('+23 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Software Architect',
        'company' => 'Blueprint Technologies',
        'logo' => 'https://ui-avatars.com/api/?name=BT&background=5B21B6&color=fff&size=128',
        'location' => 'Seattle',
        'job_type' => 'Full-time',
        'salary' => '$160,000 - $200,000',
        'description' => 'Define the technical architecture for complex software systems. Make high-level design choices and dictate technical standards, including tools and platforms.',
        'skills' => json_encode(['Software Architecture', 'System Design', 'Microservices', 'Cloud Platforms', 'Design Patterns', 'Scalability', 'Performance']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-14 days')),
        'expires_at' => date('Y-m-d', strtotime('+16 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Executive Assistant',
        'company' => 'Global Corp',
        'logo' => 'https://ui-avatars.com/api/?name=GC&background=1E40AF&color=fff&size=128',
        'location' => 'New York',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $90,000',
        'description' => 'Provide high-level administrative support to C-suite executives. Manage calendars, coordinate travel, prepare reports, and handle confidential information.',
        'skills' => json_encode(['Executive Support', 'Calendar Management', 'Travel Coordination', 'Communication', 'Organization', 'Microsoft Office Suite', 'Discretion']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-3 days')),
        'expires_at' => date('Y-m-d', strtotime('+27 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'DevOps Engineer (Azure)',
        'company' => 'Azure Cloud Partners',
        'logo' => 'https://ui-avatars.com/api/?name=AC&background=0D8ABC&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$115,000 - $145,000',
        'description' => 'Implement and manage CI/CD pipelines, infrastructure automation, and monitoring solutions on Microsoft Azure. Experience with Azure DevOps, ARM templates, and PowerShell.',
        'skills' => json_encode(['Azure', 'DevOps', 'Azure DevOps', 'ARM Templates', 'PowerShell', 'CI/CD', 'Docker', 'Kubernetes (AKS)']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
        'expires_at' => date('Y-m-d', strtotime('+25 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Frontend Engineer (Vue.js)',
        'company' => 'VueWorks',
        'logo' => 'https://ui-avatars.com/api/?name=VW&background=4C1D95&color=fff&size=128',
        'location' => 'Amsterdam',
        'job_type' => 'Full-time',
        'salary' => '€65,000 - €85,000',
        'description' => 'Develop modern web applications using Vue.js and related ecosystem (Vuex, Vue Router). Collaborate with designers and backend developers.',
        'skills' => json_encode(['Vue.js', 'JavaScript', 'HTML', 'CSS', 'Vuex', 'Vue Router', 'Nuxt.js', 'Git']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-16 days')),
        'expires_at' => date('Y-m-d', strtotime('+14 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Paralegal',
        'company' => 'Legal Eagles LLP',
        'logo' => 'https://ui-avatars.com/api/?name=LE&background=065F46&color=fff&size=128',
        'location' => 'Washington D.C.',
        'job_type' => 'Full-time',
        'salary' => '$60,000 - $80,000',
        'description' => 'Assist attorneys with legal research, document preparation, case management, and client communication. Paralegal certification required.',
        'skills' => json_encode(['Paralegal', 'Legal Research', 'Document Drafting', 'Case Management', 'Litigation Support', 'Westlaw/LexisNexis']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-19 days')),
        'expires_at' => date('Y-m-d', strtotime('+11 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Account Executive',
        'company' => 'SalesForce Solutions',
        'logo' => 'https://ui-avatars.com/api/?name=SF&background=9D174D&color=fff&size=128',
        'location' => 'Chicago',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $90,000 + Commission',
        'description' => 'Manage the full sales cycle from prospecting to closing deals. Build relationships with clients and achieve sales targets. Experience with CRM software (Salesforce).',
        'skills' => json_encode(['Sales', 'Account Executive', 'Closing Deals', 'Relationship Building', 'CRM', 'Salesforce', 'Negotiation']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-2 days')),
        'expires_at' => date('Y-m-d', strtotime('+28 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Security Engineer',
        'company' => 'Fortress Security',
        'logo' => 'https://ui-avatars.com/api/?name=FS&background=1E3A8A&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$110,000 - $140,000',
        'description' => 'Design, implement, and manage security infrastructure and tools. Conduct security assessments, vulnerability management, and incident response.',
        'skills' => json_encode(['Security Engineering', 'Network Security', 'Cloud Security', 'Vulnerability Management', 'Incident Response', 'SIEM', 'Firewalls']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-13 days')),
        'expires_at' => date('Y-m-d', strtotime('+17 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Office Manager',
        'company' => 'Smooth Operations Co.',
        'logo' => 'https://ui-avatars.com/api/?name=SO&background=7C2D12&color=fff&size=128',
        'location' => 'Austin',
        'job_type' => 'Full-time',
        'salary' => '$55,000 - $70,000',
        'description' => 'Oversee daily office operations, manage supplies, coordinate vendors, support staff, and ensure a productive work environment. Strong organizational skills.',
        'skills' => json_encode(['Office Management', 'Administration', 'Vendor Management', 'Organization', 'Communication', 'Microsoft Office']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-21 days')),
        'expires_at' => date('Y-m-d', strtotime('+9 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Full Stack Developer (PHP/Laravel)',
        'company' => 'Web Artisans',
        'logo' => 'https://ui-avatars.com/api/?name=WA&background=5B21B6&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$90,000 - $120,000',
        'description' => 'Develop and maintain web applications using PHP, Laravel, and Vue.js/React. Experience with MySQL and REST APIs required.',
        'skills' => json_encode(['PHP', 'Laravel', 'MySQL', 'JavaScript', 'Vue.js', 'React', 'Full Stack Development', 'API Development']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'expires_at' => date('Y-m-d', strtotime('+29 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Biomedical Engineer',
        'company' => 'MedTech Innovations',
        'logo' => 'https://ui-avatars.com/api/?name=MI&background=1E40AF&color=fff&size=128',
        'location' => 'Boston',
        'job_type' => 'Full-time',
        'salary' => '$85,000 - $110,000',
        'description' => 'Design, develop, and test medical devices and equipment. Knowledge of FDA regulations and experience with CAD software (SolidWorks) preferred.',
        'skills' => json_encode(['Biomedical Engineering', 'Medical Devices', 'Design Controls', 'FDA Regulations', 'CAD', 'SolidWorks', 'Testing']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-24 days')),
        'expires_at' => date('Y-m-d', strtotime('+6 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Environmental Scientist',
        'company' => 'Eco Solutions Group',
        'logo' => 'https://ui-avatars.com/api/?name=ES&background=047857&color=fff&size=128',
        'location' => 'Denver',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $90,000',
        'description' => 'Conduct environmental assessments, analyze data, and prepare reports on environmental impact. Knowledge of regulations (NEPA, ESA) required.',
        'skills' => json_encode(['Environmental Science', 'Data Analysis', 'Field Sampling', 'GIS', 'NEPA', 'Report Writing', 'Environmental Regulations']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-10 days')),
        'expires_at' => date('Y-m-d', strtotime('+20 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Mechanical Engineer',
        'company' => 'Precision Mechanics',
        'logo' => 'https://ui-avatars.com/api/?name=PM&background=6D28D9&color=fff&size=128',
        'location' => 'Detroit',
        'job_type' => 'Full-time',
        'salary' => '$80,000 - $105,000',
        'description' => 'Design, analyze, and test mechanical components and systems. Proficiency in CAD software (e.g., AutoCAD, SolidWorks) and FEA tools.',
        'skills' => json_encode(['Mechanical Engineering', 'CAD', 'SolidWorks', 'FEA', 'Thermodynamics', 'Product Design', 'Manufacturing Processes']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-15 days')),
        'expires_at' => date('Y-m-d', strtotime('+15 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Electrical Engineer',
        'company' => 'Circuit Masters',
        'logo' => 'https://ui-avatars.com/api/?name=CM&background=BE123C&color=fff&size=128',
        'location' => 'San Jose',
        'job_type' => 'Full-time',
        'salary' => '$95,000 - $125,000',
        'description' => 'Design, develop, and test electrical systems and components. Experience with circuit design, PCB layout, and testing equipment.',
        'skills' => json_encode(['Electrical Engineering', 'Circuit Design', 'PCB Layout', 'Altium Designer', 'Power Electronics', 'Signal Processing', 'Testing']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
        'expires_at' => date('Y-m-d', strtotime('+25 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Civil Engineer',
        'company' => 'Infrastructure Builders',
        'logo' => 'https://ui-avatars.com/api/?name=IB&background=1D4ED8&color=fff&size=128',
        'location' => 'Houston',
        'job_type' => 'Full-time',
        'salary' => '$85,000 - $110,000',
        'description' => 'Plan, design, and oversee construction and maintenance of infrastructure projects (roads, bridges, buildings). PE license preferred.',
        'skills' => json_encode(['Civil Engineering', 'Structural Analysis', 'AutoCAD Civil 3D', 'Project Management', 'Construction Management', 'Geotechnical Engineering']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-20 days')),
        'expires_at' => date('Y-m-d', strtotime('+10 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Chemical Engineer',
        'company' => 'Chem Process Solutions',
        'logo' => 'https://ui-avatars.com/api/?name=CP&background=B45309&color=fff&size=128',
        'location' => 'Philadelphia',
        'job_type' => 'Full-time',
        'salary' => '$90,000 - $115,000',
        'description' => 'Design and optimize chemical processes, manage plant operations, and ensure safety compliance. Experience with process simulation software (Aspen Plus).',
        'skills' => json_encode(['Chemical Engineering', 'Process Design', 'Process Simulation', 'Aspen Plus', 'Plant Operations', 'Safety Management', 'Thermodynamics']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-8 days')),
        'expires_at' => date('Y-m-d', strtotime('+22 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Aerospace Engineer',
        'company' => 'Aero Dynamics Corp',
        'logo' => 'https://ui-avatars.com/api/?name=AD&background=500724&color=fff&size=128',
        'location' => 'Seattle',
        'job_type' => 'Full-time',
        'salary' => '$100,000 - $130,000',
        'description' => 'Design, develop, and test aircraft and spacecraft systems. Knowledge of aerodynamics, propulsion, and materials science.',
        'skills' => json_encode(['Aerospace Engineering', 'Aerodynamics', 'Propulsion Systems', 'Structural Analysis', 'MATLAB', 'CATIA', 'Flight Dynamics']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-12 days')),
        'expires_at' => date('Y-m-d', strtotime('+18 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Industrial Engineer',
        'company' => 'Optimize Manufacturing',
        'logo' => 'https://ui-avatars.com/api/?name=OM&background=065F46&color=fff&size=128',
        'location' => 'Chicago',
        'job_type' => 'Full-time',
        'salary' => '$75,000 - $95,000',
        'description' => 'Improve efficiency and productivity in manufacturing processes. Analyze workflows, implement lean methodologies, and optimize supply chains.',
        'skills' => json_encode(['Industrial Engineering', 'Process Improvement', 'Lean Manufacturing', 'Six Sigma', 'Supply Chain Management', 'Operations Research', 'Simulation']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-2 days')),
        'expires_at' => date('Y-m-d', strtotime('+28 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Petroleum Engineer',
        'company' => 'Energy Resources Inc.',
        'logo' => 'https://ui-avatars.com/api/?name=ER&background=7F1D1D&color=fff&size=128',
        'location' => 'Houston',
        'job_type' => 'Full-time',
        'salary' => '$110,000 - $150,000',
        'description' => 'Design and manage drilling operations, optimize oil and gas production, and analyze reservoir performance. Experience with industry software.',
        'skills' => json_encode(['Petroleum Engineering', 'Drilling Operations', 'Reservoir Engineering', 'Production Optimization', 'Well Logging', 'Petrel']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-25 days')),
        'expires_at' => date('Y-m-d', strtotime('+5 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Nuclear Engineer',
        'company' => 'Atomic Power Group',
        'logo' => 'https://ui-avatars.com/api/?name=AP&background=1E3A8A&color=fff&size=128',
        'location' => 'Washington D.C.',
        'job_type' => 'Full-time',
        'salary' => '$105,000 - $140,000',
        'description' => 'Design, operate, and maintain nuclear reactors and power plants. Ensure safety protocols and regulatory compliance. Knowledge of nuclear physics.',
        'skills' => json_encode(['Nuclear Engineering', 'Reactor Physics', 'Radiation Protection', 'Nuclear Safety', 'Thermal Hydraulics', 'Regulatory Compliance']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-18 days')),
        'expires_at' => date('Y-m-d', strtotime('+12 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Materials Engineer',
        'company' => 'Advanced Materials Lab',
        'logo' => 'https://ui-avatars.com/api/?name=AM&background=0D8ABC&color=fff&size=128',
        'location' => 'Boston',
        'job_type' => 'Full-time',
        'salary' => '$85,000 - $110,000',
        'description' => 'Develop, process, and test materials for specific applications. Analyze material properties and performance. Experience with characterization techniques.',
        'skills' => json_encode(['Materials Science', 'Materials Engineering', 'Metallurgy', 'Polymers', 'Ceramics', 'Material Characterization', 'SEM/TEM']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-7 days')),
        'expires_at' => date('Y-m-d', strtotime('+23 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Agricultural Engineer',
        'company' => 'FarmTech Solutions',
        'logo' => 'https://ui-avatars.com/api/?name=FS&background=166534&color=fff&size=128',
        'location' => 'Des Moines',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $90,000',
        'description' => 'Design agricultural machinery, irrigation systems, and structures. Improve farming techniques and sustainability practices.',
        'skills' => json_encode(['Agricultural Engineering', 'Farm Machinery', 'Irrigation Systems', 'Soil Science', 'Precision Agriculture', 'CAD']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-14 days')),
        'expires_at' => date('Y-m-d', strtotime('+16 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Marine Engineer',
        'company' => 'Oceanic Systems',
        'logo' => 'https://ui-avatars.com/api/?name=OS&background=0E7490&color=fff&size=128',
        'location' => 'Miami',
        'job_type' => 'Full-time',
        'salary' => '$90,000 - $120,000',
        'description' => 'Design, build, and maintain ships, submarines, and offshore structures. Knowledge of naval architecture and marine propulsion systems.',
        'skills' => json_encode(['Marine Engineering', 'Naval Architecture', 'Ship Design', 'Propulsion Systems', 'Hydrodynamics', 'Offshore Structures']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-3 days')),
        'expires_at' => date('Y-m-d', strtotime('+27 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Mining Engineer',
        'company' => 'Deep Earth Extraction',
        'logo' => 'https://ui-avatars.com/api/?name=DE&background=78350F&color=fff&size=128',
        'location' => 'Denver',
        'job_type' => 'Full-time',
        'salary' => '$95,000 - $125,000',
        'description' => 'Plan and manage mine operations, including extraction methods, safety procedures, and environmental compliance. Experience with mine planning software.',
        'skills' => json_encode(['Mining Engineering', 'Mine Planning', 'Rock Mechanics', 'Ventilation', 'Mineral Processing', 'Safety Management']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-11 days')),
        'expires_at' => date('Y-m-d', strtotime('+19 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Surveyor',
        'company' => 'Landmark Surveys',
        'logo' => 'https://ui-avatars.com/api/?name=LS&background=365314&color=fff&size=128',
        'location' => 'Austin',
        'job_type' => 'Full-time',
        'salary' => '$65,000 - $85,000',
        'description' => 'Conduct land surveys to determine property boundaries, topography, and other features. Use surveying equipment (GPS, total stations) and software.',
        'skills' => json_encode(['Land Surveying', 'Topographic Surveys', 'Boundary Surveys', 'GPS', 'Total Station', 'AutoCAD Civil 3D', 'GIS']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'expires_at' => date('Y-m-d', strtotime('+29 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Urban Planner',
        'company' => 'CityScape Design',
        'logo' => 'https://ui-avatars.com/api/?name=CD&background=4C1D95&color=fff&size=128',
        'location' => 'Portland',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $90,000',
        'description' => 'Develop plans for land use, transportation systems, and community development. Analyze demographic data and zoning regulations. AICP certification preferred.',
        'skills' => json_encode(['Urban Planning', 'Land Use Planning', 'Transportation Planning', 'GIS', 'Community Development', 'Zoning', 'Public Policy']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-16 days')),
        'expires_at' => date('Y-m-d', strtotime('+14 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Landscape Architect',
        'company' => 'Green Spaces Studio',
        'logo' => 'https://ui-avatars.com/api/?name=GS&background=15803D&color=fff&size=128',
        'location' => 'San Francisco',
        'job_type' => 'Full-time',
        'salary' => '$75,000 - $95,000',
        'description' => 'Design outdoor spaces, parks, and public areas. Create site plans, planting designs, and construction documents. PLA license required.',
        'skills' => json_encode(['Landscape Architecture', 'Site Design', 'Planting Design', 'AutoCAD', 'SketchUp', 'Horticulture', 'Construction Documentation']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-9 days')),
        'expires_at' => date('Y-m-d', strtotime('+21 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Interior Designer',
        'company' => 'Style & Space Interiors',
        'logo' => 'https://ui-avatars.com/api/?name=SS&background=9D174D&color=fff&size=128',
        'location' => 'New York',
        'job_type' => 'Full-time',
        'salary' => '$60,000 - $80,000',
        'description' => 'Design functional and aesthetically pleasing interior spaces for residential or commercial clients. Select furnishings, materials, and finishes. Proficiency in design software.',
        'skills' => json_encode(['Interior Design', 'Space Planning', 'AutoCAD', 'Revit', 'SketchUp', 'Material Selection', 'Client Presentation']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-4 days')),
        'expires_at' => date('Y-m-d', strtotime('+26 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Architect',
        'company' => 'Modern Structures Group',
        'logo' => 'https://ui-avatars.com/api/?name=MS&background=1E3A8A&color=fff&size=128',
        'location' => 'Chicago',
        'job_type' => 'Full-time',
        'salary' => '$80,000 - $110,000',
        'description' => 'Design buildings and structures, create architectural drawings and models, and oversee construction projects. Licensed architect preferred.',
        'skills' => json_encode(['Architecture', 'Building Design', 'Revit', 'AutoCAD', 'SketchUp', 'Construction Documents', 'Building Codes']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-19 days')),
        'expires_at' => date('Y-m-d', strtotime('+11 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Construction Manager',
        'company' => 'BuildRight Construction',
        'logo' => 'https://ui-avatars.com/api/?name=BR&background=7C2D12&color=fff&size=128',
        'location' => 'Dallas',
        'job_type' => 'Full-time',
        'salary' => '$90,000 - $120,000',
        'description' => 'Oversee construction projects from planning to completion. Manage budgets, schedules, subcontractors, and ensure safety compliance.',
        'skills' => json_encode(['Construction Management', 'Project Management', 'Scheduling', 'Budgeting', 'Contract Negotiation', 'Safety Management', 'Blueprint Reading']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-6 days')),
        'expires_at' => date('Y-m-d', strtotime('+24 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Actuary',
        'company' => 'Risk Analytics Partners',
        'logo' => 'https://ui-avatars.com/api/?name=RA&background=5B21B6&color=fff&size=128',
        'location' => 'Hartford',
        'job_type' => 'Full-time',
        'salary' => '$100,000 - $140,000',
        'description' => 'Analyze financial risks using mathematics, statistics, and financial theory. Develop insurance policies and pension plans. ASA or FSA designation required.',
        'skills' => json_encode(['Actuarial Science', 'Risk Management', 'Statistical Modeling', 'Financial Mathematics', 'Insurance', 'Excel', 'SQL']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-13 days')),
        'expires_at' => date('Y-m-d', strtotime('+17 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Statistician',
        'company' => 'Data Insights Co.',
        'logo' => 'https://ui-avatars.com/api/?name=DI&background=1E40AF&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$85,000 - $115,000',
        'description' => 'Apply statistical methods to collect, analyze, and interpret data. Design experiments and surveys. Proficiency in R or SAS required.',
        'skills' => json_encode(['Statistics', 'Data Analysis', 'R', 'SAS', 'Statistical Modeling', 'Experimental Design', 'Survey Methodology']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-22 days')),
        'expires_at' => date('Y-m-d', strtotime('+8 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Mathematician',
        'company' => 'Applied Logic Research',
        'logo' => 'https://ui-avatars.com/api/?name=AL&background=0D8ABC&color=fff&size=128',
        'location' => 'Cambridge',
        'job_type' => 'Full-time',
        'salary' => '$90,000 - $120,000',
        'description' => 'Conduct research in fundamental mathematics or apply mathematical techniques to solve problems in science, engineering, or business. PhD often required.',
        'skills' => json_encode(['Mathematics', 'Mathematical Modeling', 'Algorithm Development', 'Data Analysis', 'MATLAB', 'Python', 'Research']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'expires_at' => date('Y-m-d', strtotime('+29 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Physicist',
        'company' => 'Quantum Dynamics Lab',
        'logo' => 'https://ui-avatars.com/api/?name=QD&background=4C1D95&color=fff&size=128',
        'location' => 'Berkeley',
        'job_type' => 'Full-time',
        'salary' => '$95,000 - $130,000',
        'description' => 'Conduct research into physical phenomena, develop theories, and design experiments. Requires advanced degree in physics.',
        'skills' => json_encode(['Physics', 'Research', 'Experimental Design', 'Data Analysis', 'Mathematical Modeling', 'Quantum Mechanics', 'Optics']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-10 days')),
        'expires_at' => date('Y-m-d', strtotime('+20 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Chemist',
        'company' => 'Molecular Solutions Inc.',
        'logo' => 'https://ui-avatars.com/api/?name=MS&background=065F46&color=fff&size=128',
        'location' => 'San Diego',
        'job_type' => 'Full-time',
        'salary' => '$80,000 - $105,000',
        'description' => 'Conduct research, analysis, and experimentation on chemical substances. Develop new products and processes. Experience with analytical instruments (HPLC, GC-MS).',
        'skills' => json_encode(['Chemistry', 'Organic Chemistry', 'Analytical Chemistry', 'HPLC', 'GC-MS', 'Spectroscopy', 'Laboratory Techniques']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-17 days')),
        'expires_at' => date('Y-m-d', strtotime('+13 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Biologist',
        'company' => 'Life Science Research',
        'logo' => 'https://ui-avatars.com/api/?name=LS&background=9D174D&color=fff&size=128',
        'location' => 'Boston',
        'job_type' => 'Full-time',
        'salary' => '$75,000 - $100,000',
        'description' => 'Study living organisms and their relationship to the environment. Conduct research, collect data, and perform experiments. Specialization (e.g., molecular biology, ecology) common.',
        'skills' => json_encode(['Biology', 'Molecular Biology', 'Cell Biology', 'Genetics', 'Microscopy', 'PCR', 'Data Analysis']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
        'expires_at' => date('Y-m-d', strtotime('+25 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Geologist',
        'company' => 'Earth Exploration Co.',
        'logo' => 'https://ui-avatars.com/api/?name=EE&background=1E3A8A&color=fff&size=128',
        'location' => 'Denver',
        'job_type' => 'Full-time',
        'salary' => '$80,000 - $110,000',
        'description' => 'Study the Earth\'s structure, materials, and processes. Conduct fieldwork, analyze samples, and map geological formations. Experience with GIS.',
        'skills' => json_encode(['Geology', 'Field Mapping', 'Mineralogy', 'Petrology', 'Structural Geology', 'GIS', 'Hydrogeology']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-12 days')),
        'expires_at' => date('Y-m-d', strtotime('+18 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Meteorologist',
        'company' => 'Weather Watch Inc.',
        'logo' => 'https://ui-avatars.com/api/?name=WW&background=7C2D12&color=fff&size=128',
        'location' => 'Oklahoma City',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $95,000',
        'description' => 'Study atmospheric phenomena and forecast weather conditions. Analyze weather data, use computer models, and communicate forecasts.',
        'skills' => json_encode(['Meteorology', 'Weather Forecasting', 'Atmospheric Science', 'Data Analysis', 'Numerical Weather Prediction', 'Doppler Radar']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-20 days')),
        'expires_at' => date('Y-m-d', strtotime('+10 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Astronomer',
        'company' => 'Cosmic Discoveries Institute',
        'logo' => 'https://ui-avatars.com/api/?name=CD&background=5B21B6&color=fff&size=128',
        'location' => 'Pasadena',
        'job_type' => 'Full-time',
        'salary' => '$90,000 - $125,000',
        'description' => 'Study celestial objects and phenomena. Analyze data from telescopes and satellites. Requires PhD in Astronomy or Astrophysics.',
        'skills' => json_encode(['Astronomy', 'Astrophysics', 'Data Analysis', 'Observational Astronomy', 'Python', 'Research', 'Telescopes']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-8 days')),
        'expires_at' => date('Y-m-d', strtotime('+22 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Pharmacist',
        'company' => 'Community Health Pharmacy',
        'logo' => 'https://ui-avatars.com/api/?name=CH&background=1E40AF&color=fff&size=128',
        'location' => 'Chicago',
        'job_type' => 'Full-time',
        'salary' => '$115,000 - $140,000',
        'description' => 'Dispense prescription medications, counsel patients on drug use, and manage pharmacy operations. PharmD degree and state license required.',
        'skills' => json_encode(['Pharmacy', 'Pharmacology', 'Patient Counseling', 'Medication Therapy Management', 'Dispensing', 'Pharmacy Law']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-15 days')),
        'expires_at' => date('Y-m-d', strtotime('+15 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Veterinarian',
        'company' => 'Animal Care Clinic',
        'logo' => 'https://ui-avatars.com/api/?name=AC&background=0D8ABC&color=fff&size=128',
        'location' => 'Austin',
        'job_type' => 'Full-time',
        'salary' => '$90,000 - $120,000',
        'description' => 'Diagnose and treat illnesses and injuries in animals. Perform surgery, administer vaccinations, and advise owners. DVM degree and license required.',
        'skills' => json_encode(['Veterinary Medicine', 'Animal Surgery', 'Diagnostics', 'Animal Husbandry', 'Client Communication', 'Pharmacology']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-2 days')),
        'expires_at' => date('Y-m-d', strtotime('+28 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Dentist',
        'company' => 'Smile Bright Dental',
        'logo' => 'https://ui-avatars.com/api/?name=SB&background=4C1D95&color=fff&size=128',
        'location' => 'Los Angeles',
        'job_type' => 'Full-time',
        'salary' => '$150,000 - $200,000',
        'description' => 'Diagnose and treat problems with teeth and gums. Perform cleanings, fillings, extractions, and other dental procedures. DDS or DMD degree required.',
        'skills' => json_encode(['Dentistry', 'Oral Surgery', 'Restorative Dentistry', 'Endodontics', 'Periodontics', 'Patient Care']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-10 days')),
        'expires_at' => date('Y-m-d', strtotime('+20 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Registered Nurse (RN)',
        'company' => 'Metro General Hospital',
        'logo' => 'https://ui-avatars.com/api/?name=MG&background=065F46&color=fff&size=128',
        'location' => 'New York',
        'job_type' => 'Full-time',
        'salary' => '$75,000 - $95,000',
        'description' => 'Provide direct patient care, administer medications, monitor vital signs, and collaborate with physicians. RN license required.',
        'skills' => json_encode(['Nursing', 'Patient Care', 'Medication Administration', 'Vital Signs Monitoring', 'Electronic Health Records (EHR)', 'Patient Assessment']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'expires_at' => date('Y-m-d', strtotime('+29 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Physical Therapist',
        'company' => 'Rehab Dynamics',
        'logo' => 'https://ui-avatars.com/api/?name=RD&background=9D174D&color=fff&size=128',
        'location' => 'San Diego',
        'job_type' => 'Full-time',
        'salary' => '$80,000 - $100,000',
        'description' => 'Help patients recover from injuries and illnesses through exercise and rehabilitation techniques. Develop treatment plans. DPT degree and license required.',
        'skills' => json_encode(['Physical Therapy', 'Rehabilitation', 'Therapeutic Exercise', 'Manual Therapy', 'Patient Assessment', 'Treatment Planning']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-18 days')),
        'expires_at' => date('Y-m-d', strtotime('+12 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Occupational Therapist',
        'company' => 'Functional Living Center',
        'logo' => 'https://ui-avatars.com/api/?name=FL&background=1E3A8A&color=fff&size=128',
        'location' => 'Chicago',
        'job_type' => 'Full-time',
        'salary' => '$75,000 - $95,000',
        'description' => 'Help patients develop, recover, or maintain daily living and work skills. Assess patient needs and create therapy plans. Master\'s degree and license required.',
        'skills' => json_encode(['Occupational Therapy', 'Activities of Daily Living (ADL)', 'Patient Assessment', 'Treatment Planning', 'Rehabilitation', 'Pediatrics/Geriatrics']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-6 days')),
        'expires_at' => date('Y-m-d', strtotime('+24 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Speech-Language Pathologist',
        'company' => 'Clear Communication Clinic',
        'logo' => 'https://ui-avatars.com/api/?name=CC&background=7C2D12&color=fff&size=128',
        'location' => 'Boston',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $90,000',
        'description' => 'Diagnose and treat communication and swallowing disorders. Work with patients of all ages. Master\'s degree and CCC-SLP required.',
        'skills' => json_encode(['Speech Therapy', 'Language Disorders', 'Swallowing Disorders (Dysphagia)', 'Articulation Therapy', 'Patient Assessment', 'ASHA CCC-SLP']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-14 days')),
        'expires_at' => date('Y-m-d', strtotime('+16 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Medical Assistant',
        'company' => 'Primary Care Associates',
        'logo' => 'https://ui-avatars.com/api/?name=PC&background=5B21B6&color=fff&size=128',
        'location' => 'Atlanta',
        'job_type' => 'Full-time',
        'salary' => '$35,000 - $45,000',
        'description' => 'Perform administrative and clinical tasks in a healthcare setting. Take vital signs, assist with procedures, schedule appointments. Certification preferred.',
        'skills' => json_encode(['Medical Assisting', 'Vital Signs', 'Phlebotomy', 'Patient Intake', 'Scheduling', 'EHR', 'Medical Terminology']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-3 days')),
        'expires_at' => date('Y-m-d', strtotime('+27 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Teacher (High School Math)',
        'company' => 'Central High School District',
        'logo' => 'https://ui-avatars.com/api/?name=CH&background=1E40AF&color=fff&size=128',
        'location' => 'Denver',
        'job_type' => 'Full-time',
        'salary' => '$50,000 - $70,000',
        'description' => 'Teach mathematics courses to high school students. Develop lesson plans, grade assignments, and manage classroom activities. State teaching license required.',
        'skills' => json_encode(['Teaching', 'Mathematics Education', 'Lesson Planning', 'Classroom Management', 'Curriculum Development', 'Algebra/Geometry/Calculus']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-19 days')),
        'expires_at' => date('Y-m-d', strtotime('+11 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Librarian',
        'company' => 'City Public Library',
        'logo' => 'https://ui-avatars.com/api/?name=CP&background=0D8ABC&color=fff&size=128',
        'location' => 'Seattle',
        'job_type' => 'Full-time',
        'salary' => '$55,000 - $75,000',
        'description' => 'Manage library collections, assist patrons with research, organize programs, and manage library resources. MLS degree required.',
        'skills' => json_encode(['Librarianship', 'Information Literacy', 'Cataloging', 'Collection Development', 'Reference Services', 'Database Searching']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-7 days')),
        'expires_at' => date('Y-m-d', strtotime('+23 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Chef',
        'company' => 'Gourmet Bistro',
        'logo' => 'https://ui-avatars.com/api/?name=GB&background=4C1D95&color=fff&size=128',
        'location' => 'New Orleans',
        'job_type' => 'Full-time',
        'salary' => '$60,000 - $80,000',
        'description' => 'Lead kitchen operations, create menus, manage inventory, and ensure food quality and safety standards. Culinary degree and experience required.',
        'skills' => json_encode(['Culinary Arts', 'Menu Development', 'Kitchen Management', 'Food Costing', 'Inventory Management', 'Food Safety', 'Cooking Techniques']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-16 days')),
        'expires_at' => date('Y-m-d', strtotime('+14 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Police Officer',
        'company' => 'City Police Department',
        'logo' => 'https://ui-avatars.com/api/?name=PD&background=065F46&color=fff&size=128',
        'location' => 'Chicago',
        'job_type' => 'Full-time',
        'salary' => '$60,000 - $85,000',
        'description' => 'Enforce laws, respond to calls for service, conduct investigations, and ensure public safety. Requires academy training and passing exams.',
        'skills' => json_encode(['Law Enforcement', 'Patrol Procedures', 'Criminal Investigation', 'Report Writing', 'Firearms Proficiency', 'Emergency Response']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-23 days')),
        'expires_at' => date('Y-m-d', strtotime('+7 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Firefighter',
        'company' => 'City Fire Department',
        'logo' => 'https://ui-avatars.com/api/?name=FD&background=991B1B&color=fff&size=128',
        'location' => 'Los Angeles',
        'job_type' => 'Full-time',
        'salary' => '$65,000 - $90,000',
        'description' => 'Respond to fires and other emergencies, perform rescue operations, and provide medical assistance. Requires academy training and certifications (EMT).',
        'skills' => json_encode(['Firefighting', 'Emergency Medical Services (EMS)', 'Rescue Operations', 'Hazardous Materials (HazMat)', 'Equipment Operation', 'Teamwork']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-4 days')),
        'expires_at' => date('Y-m-d', strtotime('+26 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Paramedic',
        'company' => 'County EMS Services',
        'logo' => 'https://ui-avatars.com/api/?name=ES&background=1E3A8A&color=fff&size=128',
        'location' => 'Miami',
        'job_type' => 'Full-time',
        'salary' => '$55,000 - $75,000',
        'description' => 'Provide advanced emergency medical care to patients in pre-hospital settings. Administer medications, perform advanced life support procedures. Paramedic certification required.',
        'skills' => json_encode(['Emergency Medical Services (EMS)', 'Paramedic', 'Advanced Life Support (ALS)', 'Patient Assessment', 'Trauma Care', 'Pharmacology']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-11 days')),
        'expires_at' => date('Y-m-d', strtotime('+19 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Pilot (Commercial)',
        'company' => 'Regional Airways',
        'logo' => 'https://ui-avatars.com/api/?name=RA&background=7C2D12&color=fff&size=128',
        'location' => 'Dallas',
        'job_type' => 'Full-time',
        'salary' => '$80,000 - $150,000+',
        'description' => 'Operate commercial aircraft for passenger or cargo transport. Ensure flight safety and adherence to regulations. Requires ATP license and type ratings.',
        'skills' => json_encode(['Aviation', 'Piloting', 'Flight Planning', 'Navigation', 'Aircraft Systems', 'FAA Regulations', 'Crew Resource Management']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-28 days')),
        'expires_at' => date('Y-m-d', strtotime('+2 days')),
        'is_active' => 0, // Expired example
    ],
    [
        'user_id' => 3,
        'title' => 'Air Traffic Controller',
        'company' => 'Federal Aviation Administration (FAA)',
        'logo' => 'https://ui-avatars.com/api/?name=FA&background=5B21B6&color=fff&size=128',
        'location' => 'Various (Nationwide)',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $130,000+',
        'description' => 'Direct aircraft movements in airspace and on the ground to ensure safety and efficiency. Requires extensive training and certification.',
        'skills' => json_encode(['Air Traffic Control', 'Aviation Safety', 'Communication', 'Decision Making', 'Radar Systems', 'Spatial Awareness']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
        'expires_at' => date('Y-m-d', strtotime('+25 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Journalist',
        'company' => 'City News Network',
        'logo' => 'https://ui-avatars.com/api/?name=CN&background=1E40AF&color=fff&size=128',
        'location' => 'New York',
        'job_type' => 'Full-time',
        'salary' => '$50,000 - $75,000',
        'description' => 'Investigate stories, conduct interviews, write news articles or produce broadcast reports. Strong writing and research skills required.',
        'skills' => json_encode(['Journalism', 'Writing', 'Interviewing', 'Research', 'Editing', 'Fact-Checking', 'Media Law']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-12 days')),
        'expires_at' => date('Y-m-d', strtotime('+18 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Photographer',
        'company' => 'Creative Lens Studio',
        'logo' => 'https://ui-avatars.com/api/?name=CL&background=0D8ABC&color=fff&size=128',
        'location' => 'Los Angeles',
        'job_type' => 'Freelance/Contract',
        'salary' => 'Project-based',
        'description' => 'Capture high-quality images for various clients (portraits, events, commercial). Proficiency in camera equipment and editing software (Lightroom, Photoshop). Portfolio required.',
        'skills' => json_encode(['Photography', 'Portrait Photography', 'Event Photography', 'Adobe Lightroom', 'Adobe Photoshop', 'Lighting', 'Composition']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-9 days')),
        'expires_at' => date('Y-m-d', strtotime('+21 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Videographer',
        'company' => 'Motion Pictures Inc.',
        'logo' => 'https://ui-avatars.com/api/?name=MP&background=4C1D95&color=fff&size=128',
        'location' => 'Remote/Travel',
        'job_type' => 'Freelance/Contract',
        'salary' => 'Project-based',
        'description' => 'Shoot and edit video content for various purposes (marketing, events, documentary). Proficiency with cameras, lighting, audio, and editing software (Premiere Pro, Final Cut Pro).',
        'skills' => json_encode(['Videography', 'Video Editing', 'Adobe Premiere Pro', 'Final Cut Pro', 'Cinematography', 'Lighting', 'Audio Recording']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'expires_at' => date('Y-m-d', strtotime('+29 days')),
        'is_active' => 1,
    ],
];

// You can add functions here to interact with this data if needed,
// or simply include this file where the $sampleJobs array is required.

?>