<?php

/**
 * Sample Job Listings Data
 *
 * This array contains sample job data for testing and demonstration purposes.
 * In a real application, this data would typically come from a database.
 */

$sampleJobs = [
    [
        'user_id' => 1, // Assuming user ID 1 is an HR/Admin who posted this
        'title' => 'Senior Frontend Developer',
        'company' => 'Innovate Solutions',
        'logo' => 'https://ui-avatars.com/api/?name=IS&background=0D8ABC&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$110,000 - $140,000',
        'description' => 'Seeking an experienced Frontend Developer to lead our UI/UX initiatives. Must be proficient in React, TypeScript, and modern CSS frameworks. Responsibilities include developing new user-facing features, building reusable code and libraries, and ensuring the technical feasibility of UI/UX designs.',
        'skills' => json_encode(['React', 'TypeScript', 'CSS', 'HTML', 'JavaScript', 'UI/UX Design', 'Git']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-3 days')),
        'expires_at' => date('Y-m-d', strtotime('+27 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2, // Assuming user ID 2 is an HR/Admin
        'title' => 'Backend Engineer (Python/Django)',
        'company' => 'Data Insights Inc.',
        'logo' => 'https://ui-avatars.com/api/?name=DI&background=4C1D95&color=fff&size=128',
        'location' => 'New York',
        'job_type' => 'Full-time',
        'salary' => '$100,000 - $130,000',
        'description' => 'Join our backend team to build scalable APIs and data processing pipelines using Python and Django. Experience with PostgreSQL and AWS is a plus. You will work closely with data scientists and frontend developers.',
        'skills' => json_encode(['Python', 'Django', 'PostgreSQL', 'API Development', 'AWS', 'REST', 'Docker']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
        'expires_at' => date('Y-m-d', strtotime('+25 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Cloud DevOps Engineer',
        'company' => 'CloudSystems Ltd.',
        'logo' => 'https://ui-avatars.com/api/?name=CS&background=065F46&color=fff&size=128',
        'location' => 'San Francisco',
        'job_type' => 'Full-time',
        'salary' => '$120,000 - $150,000',
        'description' => 'Manage and automate our cloud infrastructure on AWS. Strong experience with Terraform, Kubernetes, and CI/CD pipelines required. Implement monitoring and alerting solutions.',
        'skills' => json_encode(['AWS', 'Terraform', 'Kubernetes', 'Docker', 'CI/CD', 'Linux', 'Ansible']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'expires_at' => date('Y-m-d', strtotime('+29 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3, // Assuming user ID 3 is an HR/Admin
        'title' => 'Marketing Manager',
        'company' => 'Growth Hub',
        'logo' => 'https://ui-avatars.com/api/?name=GH&background=9D174D&color=fff&size=128',
        'location' => 'London',
        'job_type' => 'Full-time',
        'salary' => '£50,000 - £65,000',
        'description' => 'Lead our marketing campaigns across digital channels. Proven experience in SEO, SEM, and content marketing needed. Develop and execute marketing strategies to drive growth.',
        'skills' => json_encode(['Digital Marketing', 'SEO', 'SEM', 'Content Marketing', 'Social Media', 'Analytics', 'Email Marketing']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-10 days')),
        'expires_at' => date('Y-m-d', strtotime('+20 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Data Scientist',
        'company' => 'AnalyticsPro',
        'logo' => 'https://ui-avatars.com/api/?name=AP&background=1E3A8A&color=fff&size=128',
        'location' => 'Berlin',
        'job_type' => 'Full-time',
        'salary' => '€70,000 - €90,000',
        'description' => 'Develop machine learning models to extract insights from large datasets. Proficiency in Python, R, SQL, and ML frameworks required. Communicate findings to stakeholders.',
        'skills' => json_encode(['Python', 'R', 'SQL', 'Machine Learning', 'Data Analysis', 'Statistics', 'TensorFlow']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-7 days')),
        'expires_at' => date('Y-m-d', strtotime('+23 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'UI/UX Designer',
        'company' => 'Creative Minds',
        'logo' => 'https://ui-avatars.com/api/?name=CM&background=7C2D12&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Contract',
        'salary' => '$60 - $80 / hour',
        'description' => 'Design intuitive and visually appealing interfaces for web and mobile applications. Portfolio showcasing user-centered design required. Collaborate with product managers and developers.',
        'skills' => json_encode(['UI Design', 'UX Design', 'Figma', 'Sketch', 'Prototyping', 'User Research', 'Wireframing']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-2 days')),
        'expires_at' => date('Y-m-d', strtotime('+18 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Software Engineer (Java)',
        'company' => 'Enterprise Tech',
        'logo' => 'https://ui-avatars.com/api/?name=ET&background=5B21B6&color=fff&size=128',
        'location' => 'Austin',
        'job_type' => 'Full-time',
        'salary' => '$95,000 - $125,000',
        'description' => 'Develop and maintain enterprise-level applications using Java and Spring Boot. Experience with microservices and databases is essential. Write clean, maintainable code.',
        'skills' => json_encode(['Java', 'Spring Boot', 'Microservices', 'SQL', 'Hibernate', 'REST API', 'Maven']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-15 days')),
        'expires_at' => date('Y-m-d', strtotime('+15 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Product Manager',
        'company' => 'NextGen Apps',
        'logo' => 'https://ui-avatars.com/api/?name=NA&background=1E40AF&color=fff&size=128',
        'location' => 'Seattle',
        'job_type' => 'Full-time',
        'salary' => '$130,000 - $160,000',
        'description' => 'Define product strategy, roadmap, and feature requirements for our mobile applications. Strong technical background preferred. Work with cross-functional teams.',
        'skills' => json_encode(['Product Management', 'Agile', 'Roadmapping', 'User Stories', 'Market Research', 'Mobile Apps', 'JIRA']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-8 days')),
        'expires_at' => date('Y-m-d', strtotime('+22 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Junior Web Developer',
        'company' => 'WebStart Co.',
        'logo' => 'https://ui-avatars.com/api/?name=WS&background=0D8ABC&color=fff&size=128',
        'location' => 'Chicago',
        'job_type' => 'Internship',
        'salary' => '$20 - $25 / hour',
        'description' => 'Assist senior developers in building and maintaining websites. Basic knowledge of HTML, CSS, and JavaScript required. Eager to learn!',
        'skills' => json_encode(['HTML', 'CSS', 'JavaScript', 'Git']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-4 days')),
        'expires_at' => date('Y-m-d', strtotime('+26 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'HR Specialist',
        'company' => 'People First Inc.',
        'logo' => 'https://ui-avatars.com/api/?name=PF&background=4C1D95&color=fff&size=128',
        'location' => 'Boston',
        'job_type' => 'Full-time',
        'salary' => '$60,000 - $75,000',
        'description' => 'Manage recruitment, onboarding, and employee relations. Experience with HRIS systems and employment law is necessary. Support HR initiatives.',
        'skills' => json_encode(['Recruitment', 'Onboarding', 'Employee Relations', 'HRIS', 'Compliance', 'Communication']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-12 days')),
        'expires_at' => date('Y-m-d', strtotime('+18 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Mobile Developer (iOS)',
        'company' => 'AppCrafters',
        'logo' => 'https://ui-avatars.com/api/?name=AC&background=065F46&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$105,000 - $135,000',
        'description' => 'Develop native iOS applications using Swift and SwiftUI. Experience with Core Data and REST APIs needed. Collaborate with designers and backend engineers.',
        'skills' => json_encode(['iOS Development', 'Swift', 'SwiftUI', 'Core Data', 'REST API', 'Xcode', 'Git']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-6 days')),
        'expires_at' => date('Y-m-d', strtotime('+24 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Full Stack Engineer (Node.js/React)',
        'company' => 'Synergy Systems',
        'logo' => 'https://ui-avatars.com/api/?name=SS&background=9D174D&color=fff&size=128',
        'location' => 'Denver',
        'job_type' => 'Full-time',
        'salary' => '$115,000 - $145,000',
        'description' => 'Build end-to-end web applications using Node.js for the backend and React for the frontend. Experience with MongoDB and GraphQL is a plus.',
        'skills' => json_encode(['Node.js', 'React', 'JavaScript', 'MongoDB', 'GraphQL', 'Full Stack Development', 'Express.js']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-9 days')),
        'expires_at' => date('Y-m-d', strtotime('+21 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Cyber Security Analyst',
        'company' => 'SecureNet',
        'logo' => 'https://ui-avatars.com/api/?name=SN&background=1E3A8A&color=fff&size=128',
        'location' => 'Washington D.C.',
        'job_type' => 'Full-time',
        'salary' => '$90,000 - $120,000',
        'description' => 'Monitor security events, investigate incidents, and implement security controls. Certifications like CISSP or CompTIA Security+ preferred.',
        'skills' => json_encode(['Cyber Security', 'Incident Response', 'SIEM', 'Network Security', 'Vulnerability Assessment', 'Firewalls', 'Penetration Testing']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-11 days')),
        'expires_at' => date('Y-m-d', strtotime('+19 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Technical Writer',
        'company' => 'DocuTech',
        'logo' => 'https://ui-avatars.com/api/?name=DT&background=7C2D12&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Part-time',
        'salary' => '$35 - $50 / hour',
        'description' => 'Create clear and concise technical documentation, user guides, and API references for software products. Work with engineers and product managers.',
        'skills' => json_encode(['Technical Writing', 'Documentation', 'API Documentation', 'Markdown', 'Editing', 'Confluence']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
        'expires_at' => date('Y-m-d', strtotime('+25 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Database Administrator (MySQL)',
        'company' => 'Reliable Data',
        'logo' => 'https://ui-avatars.com/api/?name=RD&background=5B21B6&color=fff&size=128',
        'location' => 'Dallas',
        'job_type' => 'Full-time',
        'salary' => '$85,000 - $110,000',
        'description' => 'Manage, optimize, and secure our MySQL database infrastructure. Experience with performance tuning and backups required. Ensure high availability.',
        'skills' => json_encode(['Database Administration', 'MySQL', 'Performance Tuning', 'Backup & Recovery', 'SQL', 'Linux', 'Shell Scripting']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-14 days')),
        'expires_at' => date('Y-m-d', strtotime('+16 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Content Strategist',
        'company' => 'Engage Media',
        'logo' => 'https://ui-avatars.com/api/?name=EM&background=1E40AF&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $90,000',
        'description' => 'Develop content strategies aligned with marketing goals. Oversee content creation, distribution, and performance analysis. Strong writing and SEO skills needed.',
        'skills' => json_encode(['Content Strategy', 'Content Marketing', 'SEO', 'Writing', 'Editing', 'Analytics', 'Social Media']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-18 days')),
        'expires_at' => date('Y-m-d', strtotime('+12 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'QA Engineer (Automation)',
        'company' => 'QualityFirst Software',
        'logo' => 'https://ui-avatars.com/api/?name=QF&background=0D8ABC&color=fff&size=128',
        'location' => 'Toronto',
        'job_type' => 'Full-time',
        'salary' => '$80,000 - $105,000',
        'description' => 'Design and implement automated test suites for web applications. Experience with Selenium, Cypress, or similar tools required. Identify and report bugs.',
        'skills' => json_encode(['QA Automation', 'Selenium', 'Cypress', 'JavaScript', 'Testing Frameworks', 'Bug Tracking', 'Agile']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-20 days')),
        'expires_at' => date('Y-m-d', strtotime('+10 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Network Engineer',
        'company' => 'Connect Solutions',
        'logo' => 'https://ui-avatars.com/api/?name=CS&background=4C1D95&color=fff&size=128',
        'location' => 'Atlanta',
        'job_type' => 'Full-time',
        'salary' => '$90,000 - $115,000',
        'description' => 'Design, implement, and maintain network infrastructure. Experience with Cisco routers/switches, firewalls, and VPNs required. CCNA/CCNP preferred.',
        'skills' => json_encode(['Network Engineering', 'Cisco IOS', 'Routing', 'Switching', 'Firewalls', 'VPN', 'TCP/IP']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-22 days')),
        'expires_at' => date('Y-m-d', strtotime('+8 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Business Analyst',
        'company' => 'Strategic Insights',
        'logo' => 'https://ui-avatars.com/api/?name=SI&background=065F46&color=fff&size=128',
        'location' => 'Chicago',
        'job_type' => 'Full-time',
        'salary' => '$75,000 - $95,000',
        'description' => 'Gather and analyze business requirements, document processes, and facilitate communication between stakeholders and technical teams. Strong analytical skills needed.',
        'skills' => json_encode(['Business Analysis', 'Requirements Gathering', 'Process Modeling', 'SQL', 'Data Analysis', 'Communication', 'Agile']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-25 days')),
        'expires_at' => date('Y-m-d', strtotime('+5 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Mobile Developer (Android)',
        'company' => 'DroidWorks',
        'logo' => 'https://ui-avatars.com/api/?name=DW&background=9D174D&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$100,000 - $130,000',
        'description' => 'Develop native Android applications using Kotlin and Jetpack Compose. Experience with MVVM architecture and REST APIs required.',
        'skills' => json_encode(['Android Development', 'Kotlin', 'Jetpack Compose', 'MVVM', 'REST API', 'Android Studio', 'Git']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-3 days')),
        'expires_at' => date('Y-m-d', strtotime('+27 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Systems Administrator',
        'company' => 'InfraServe',
        'logo' => 'https://ui-avatars.com/api/?name=IS&background=1E3A8A&color=fff&size=128',
        'location' => 'Phoenix',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $90,000',
        'description' => 'Manage Windows and Linux server environments, including patching, monitoring, and troubleshooting. Experience with Active Directory and virtualization.',
        'skills' => json_encode(['System Administration', 'Windows Server', 'Linux', 'Active Directory', 'VMware', 'Networking', 'Scripting']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-28 days')),
        'expires_at' => date('Y-m-d', strtotime('+2 days')),
        'is_active' => 0, // Example of an inactive/expired job
    ],
    [
        'user_id' => 3,
        'title' => 'Graphic Designer',
        'company' => 'Visual Concepts',
        'logo' => 'https://ui-avatars.com/api/?name=VC&background=7C2D12&color=fff&size=128',
        'location' => 'Los Angeles',
        'job_type' => 'Contract',
        'salary' => '$50 - $70 / hour',
        'description' => 'Create compelling visual assets for marketing campaigns, websites, and social media. Proficiency in Adobe Creative Suite required. Portfolio needed.',
        'skills' => json_encode(['Graphic Design', 'Adobe Photoshop', 'Adobe Illustrator', 'Branding', 'Typography', 'Layout Design']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'expires_at' => date('Y-m-d', strtotime('+29 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Sales Development Representative',
        'company' => 'LeadGen Pro',
        'logo' => 'https://ui-avatars.com/api/?name=LG&background=5B21B6&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$50,000 - $65,000 + Commission',
        'description' => 'Generate qualified leads for the sales team through outbound prospecting (email, calls, social). Excellent communication skills required.',
        'skills' => json_encode(['Sales Development', 'Lead Generation', 'Prospecting', 'Cold Calling', 'Email Outreach', 'CRM', 'Communication']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-10 days')),
        'expires_at' => date('Y-m-d', strtotime('+20 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Machine Learning Engineer',
        'company' => 'AI Innovations',
        'logo' => 'https://ui-avatars.com/api/?name=AI&background=1E40AF&color=fff&size=128',
        'location' => 'Palo Alto',
        'job_type' => 'Full-time',
        'salary' => '$140,000 - $180,000',
        'description' => 'Design, build, and deploy machine learning models into production systems. Strong background in software engineering and ML frameworks (TensorFlow, PyTorch).',
        'skills' => json_encode(['Machine Learning', 'Python', 'TensorFlow', 'PyTorch', 'Software Engineering', 'Cloud Platforms', 'MLOps']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-15 days')),
        'expires_at' => date('Y-m-d', strtotime('+15 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Customer Success Manager',
        'company' => 'ClientFirst SaaS',
        'logo' => 'https://ui-avatars.com/api/?name=CF&background=0D8ABC&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$75,000 - $95,000',
        'description' => 'Build relationships with key clients, ensure they achieve their desired outcomes using our software, and drive renewals and upsells. Strong communication skills.',
        'skills' => json_encode(['Customer Success', 'Account Management', 'SaaS', 'Relationship Building', 'Communication', 'CRM']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
        'expires_at' => date('Y-m-d', strtotime('+25 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'IT Support Specialist',
        'company' => 'HelpDesk Heroes',
        'logo' => 'https://ui-avatars.com/api/?name=HH&background=4C1D95&color=fff&size=128',
        'location' => 'Miami',
        'job_type' => 'Full-time',
        'salary' => '$50,000 - $65,000',
        'description' => 'Provide technical support to end-users for hardware, software, and network issues. Troubleshoot problems and escalate when necessary. Excellent customer service skills.',
        'skills' => json_encode(['IT Support', 'Troubleshooting', 'Windows', 'MacOS', 'Active Directory', 'Networking Basics', 'Customer Service']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-8 days')),
        'expires_at' => date('Y-m-d', strtotime('+22 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Blockchain Developer',
        'company' => 'Decentralized Future',
        'logo' => 'https://ui-avatars.com/api/?name=DF&background=065F46&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$120,000 - $160,000',
        'description' => 'Develop smart contracts and decentralized applications (dApps) on Ethereum or other blockchain platforms. Experience with Solidity and Web3.js/Ethers.js.',
        'skills' => json_encode(['Blockchain', 'Solidity', 'Ethereum', 'Smart Contracts', 'Web3.js', 'Cryptography', 'Node.js']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-12 days')),
        'expires_at' => date('Y-m-d', strtotime('+18 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Social Media Manager',
        'company' => 'Viral Buzz Agency',
        'logo' => 'https://ui-avatars.com/api/?name=VB&background=9D174D&color=fff&size=128',
        'location' => 'New York',
        'job_type' => 'Full-time',
        'salary' => '$60,000 - $75,000',
        'description' => 'Manage social media presence across platforms (Facebook, Instagram, Twitter, LinkedIn). Create engaging content, run campaigns, and analyze performance.',
        'skills' => json_encode(['Social Media Marketing', 'Content Creation', 'Community Management', 'Analytics', 'Copywriting', 'Hootsuite']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-2 days')),
        'expires_at' => date('Y-m-d', strtotime('+28 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Project Manager (Software)',
        'company' => 'AgileFlow Solutions',
        'logo' => 'https://ui-avatars.com/api/?name=AF&background=1E3A8A&color=fff&size=128',
        'location' => 'San Jose',
        'job_type' => 'Full-time',
        'salary' => '$100,000 - $130,000',
        'description' => 'Manage software development projects using Agile methodologies. Coordinate sprints, manage backlogs, and ensure timely delivery. PMP or Scrum Master certification is a plus.',
        'skills' => json_encode(['Project Management', 'Agile', 'Scrum', 'JIRA', 'Software Development Lifecycle', 'Risk Management', 'Communication']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-18 days')),
        'expires_at' => date('Y-m-d', strtotime('+12 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Data Engineer',
        'company' => 'Pipeline Pros',
        'logo' => 'https://ui-avatars.com/api/?name=PP&background=7C2D12&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$110,000 - $140,000',
        'description' => 'Build and maintain scalable data pipelines for ingestion, processing, and storage. Experience with ETL tools, Spark, Kafka, and cloud data warehouses (Snowflake, BigQuery).',
        'skills' => json_encode(['Data Engineering', 'ETL', 'Python', 'SQL', 'Apache Spark', 'Kafka', 'AWS', 'Airflow']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-6 days')),
        'expires_at' => date('Y-m-d', strtotime('+24 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Financial Analyst',
        'company' => 'Capital Growth Partners',
        'logo' => 'https://ui-avatars.com/api/?name=CG&background=5B21B6&color=fff&size=128',
        'location' => 'New York',
        'job_type' => 'Full-time',
        'salary' => '$80,000 - $100,000',
        'description' => 'Perform financial forecasting, reporting, and operational metrics tracking. Analyze financial data and create financial models for decision support. Strong Excel skills required.',
        'skills' => json_encode(['Financial Analysis', 'Financial Modeling', 'Excel', 'Forecasting', 'Budgeting', 'Accounting Principles', 'SQL']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-20 days')),
        'expires_at' => date('Y-m-d', strtotime('+10 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'UX Researcher',
        'company' => 'User Insights Lab',
        'logo' => 'https://ui-avatars.com/api/?name=UI&background=1E40AF&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Contract',
        'salary' => '$65 - $85 / hour',
        'description' => 'Conduct user research studies (interviews, surveys, usability testing) to inform product design decisions. Synthesize findings and present actionable insights.',
        'skills' => json_encode(['UX Research', 'User Interviews', 'Usability Testing', 'Survey Design', 'Qualitative Analysis', 'Quantitative Analysis', 'Persona Development']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-4 days')),
        'expires_at' => date('Y-m-d', strtotime('+26 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Embedded Systems Engineer',
        'company' => 'Core Hardware Inc.',
        'logo' => 'https://ui-avatars.com/api/?name=CH&background=0D8ABC&color=fff&size=128',
        'location' => 'San Diego',
        'job_type' => 'Full-time',
        'salary' => '$100,000 - $130,000',
        'description' => 'Design, develop, and test firmware for embedded systems. Proficiency in C/C++ and experience with microcontrollers (ARM, PIC) required. RTOS experience is a plus.',
        'skills' => json_encode(['Embedded Systems', 'C', 'C++', 'Microcontrollers', 'Firmware', 'RTOS', 'Hardware Debugging']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-22 days')),
        'expires_at' => date('Y-m-d', strtotime('+8 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Recruiter (Technical)',
        'company' => 'Talent Finders',
        'logo' => 'https://ui-avatars.com/api/?name=TF&background=4C1D95&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $90,000 + Bonus',
        'description' => 'Source, screen, and recruit technical candidates (engineers, developers, data scientists). Manage the full recruitment lifecycle. Experience with ATS systems.',
        'skills' => json_encode(['Technical Recruiting', 'Sourcing', 'Screening', 'Interviewing', 'ATS', 'LinkedIn Recruiter', 'Negotiation']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-9 days')),
        'expires_at' => date('Y-m-d', strtotime('+21 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Cloud Architect',
        'company' => 'SkyHigh Solutions',
        'logo' => 'https://ui-avatars.com/api/?name=SH&background=065F46&color=fff&size=128',
        'location' => 'Austin',
        'job_type' => 'Full-time',
        'salary' => '$150,000 - $190,000',
        'description' => 'Design and implement scalable, secure, and cost-effective cloud solutions on AWS, Azure, or GCP. Provide technical leadership and guidance. Cloud certifications required.',
        'skills' => json_encode(['Cloud Architecture', 'AWS', 'Azure', 'GCP', 'Solution Design', 'Infrastructure as Code', 'Security', 'Networking']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'expires_at' => date('Y-m-d', strtotime('+29 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Game Developer (Unity)',
        'company' => 'PixelPlay Studios',
        'logo' => 'https://ui-avatars.com/api/?name=PS&background=9D174D&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$80,000 - $110,000',
        'description' => 'Develop games using the Unity engine and C#. Implement gameplay mechanics, UI, and optimize performance for various platforms (PC, mobile).',
        'skills' => json_encode(['Game Development', 'Unity', 'C#', 'Gameplay Programming', 'UI Development', 'Optimization', 'Version Control']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-11 days')),
        'expires_at' => date('Y-m-d', strtotime('+19 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Operations Manager',
        'company' => 'Efficiency Experts',
        'logo' => 'https://ui-avatars.com/api/?name=EE&background=1E3A8A&color=fff&size=128',
        'location' => 'Denver',
        'job_type' => 'Full-time',
        'salary' => '$90,000 - $120,000',
        'description' => 'Oversee daily operations, improve processes, manage budgets, and lead operational teams. Strong leadership and problem-solving skills required.',
        'skills' => json_encode(['Operations Management', 'Process Improvement', 'Budgeting', 'Leadership', 'Logistics', 'Supply Chain', 'Problem Solving']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-25 days')),
        'expires_at' => date('Y-m-d', strtotime('+5 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'SEO Specialist',
        'company' => 'RankUp Digital',
        'logo' => 'https://ui-avatars.com/api/?name=RU&background=7C2D12&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$65,000 - $85,000',
        'description' => 'Develop and implement SEO strategies to improve organic search rankings. Conduct keyword research, on-page optimization, link building, and technical SEO audits.',
        'skills' => json_encode(['SEO', 'Keyword Research', 'On-Page Optimization', 'Link Building', 'Technical SEO', 'Google Analytics', 'SEM']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-7 days')),
        'expires_at' => date('Y-m-d', strtotime('+23 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Software Architect',
        'company' => 'Blueprint Technologies',
        'logo' => 'https://ui-avatars.com/api/?name=BT&background=5B21B6&color=fff&size=128',
        'location' => 'Seattle',
        'job_type' => 'Full-time',
        'salary' => '$160,000 - $200,000',
        'description' => 'Define the technical architecture for complex software systems. Make high-level design choices and dictate technical standards, including tools and platforms.',
        'skills' => json_encode(['Software Architecture', 'System Design', 'Microservices', 'Cloud Platforms', 'Design Patterns', 'Scalability', 'Performance']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-14 days')),
        'expires_at' => date('Y-m-d', strtotime('+16 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Executive Assistant',
        'company' => 'Global Corp',
        'logo' => 'https://ui-avatars.com/api/?name=GC&background=1E40AF&color=fff&size=128',
        'location' => 'New York',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $90,000',
        'description' => 'Provide high-level administrative support to C-suite executives. Manage calendars, coordinate travel, prepare reports, and handle confidential information.',
        'skills' => json_encode(['Executive Support', 'Calendar Management', 'Travel Coordination', 'Communication', 'Organization', 'Microsoft Office Suite', 'Discretion']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-3 days')),
        'expires_at' => date('Y-m-d', strtotime('+27 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'DevOps Engineer (Azure)',
        'company' => 'Azure Cloud Partners',
        'logo' => 'https://ui-avatars.com/api/?name=AC&background=0D8ABC&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$115,000 - $145,000',
        'description' => 'Implement and manage CI/CD pipelines, infrastructure automation, and monitoring solutions on Microsoft Azure. Experience with Azure DevOps, ARM templates, and PowerShell.',
        'skills' => json_encode(['Azure', 'DevOps', 'Azure DevOps', 'ARM Templates', 'PowerShell', 'CI/CD', 'Docker', 'Kubernetes (AKS)']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
        'expires_at' => date('Y-m-d', strtotime('+25 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Frontend Engineer (Vue.js)',
        'company' => 'VueWorks',
        'logo' => 'https://ui-avatars.com/api/?name=VW&background=4C1D95&color=fff&size=128',
        'location' => 'Amsterdam',
        'job_type' => 'Full-time',
        'salary' => '€65,000 - €85,000',
        'description' => 'Develop modern web applications using Vue.js and related ecosystem (Vuex, Vue Router). Collaborate with designers and backend developers.',
        'skills' => json_encode(['Vue.js', 'JavaScript', 'HTML', 'CSS', 'Vuex', 'Vue Router', 'Nuxt.js', 'Git']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-16 days')),
        'expires_at' => date('Y-m-d', strtotime('+14 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Paralegal',
        'company' => 'Legal Eagles LLP',
        'logo' => 'https://ui-avatars.com/api/?name=LE&background=065F46&color=fff&size=128',
        'location' => 'Washington D.C.',
        'job_type' => 'Full-time',
        'salary' => '$60,000 - $80,000',
        'description' => 'Assist attorneys with legal research, document preparation, case management, and client communication. Paralegal certification required.',
        'skills' => json_encode(['Paralegal', 'Legal Research', 'Document Drafting', 'Case Management', 'Litigation Support', 'Westlaw/LexisNexis']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-19 days')),
        'expires_at' => date('Y-m-d', strtotime('+11 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Account Executive',
        'company' => 'SalesForce Solutions',
        'logo' => 'https://ui-avatars.com/api/?name=SF&background=9D174D&color=fff&size=128',
        'location' => 'Chicago',
        'job_type' => 'Full-time',
        'salary' => '$70,000 - $90,000 + Commission',
        'description' => 'Manage the full sales cycle from prospecting to closing deals. Build relationships with clients and achieve sales targets. Experience with CRM software (Salesforce).',
        'skills' => json_encode(['Sales', 'Account Executive', 'Closing Deals', 'Relationship Building', 'CRM', 'Salesforce', 'Negotiation']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-2 days')),
        'expires_at' => date('Y-m-d', strtotime('+28 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Security Engineer',
        'company' => 'Fortress Security',
        'logo' => 'https://ui-avatars.com/api/?name=FS&background=1E3A8A&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$110,000 - $140,000',
        'description' => 'Design, implement, and manage security infrastructure and tools. Conduct security assessments, vulnerability management, and incident response.',
        'skills' => json_encode(['Security Engineering', 'Network Security', 'Cloud Security', 'Vulnerability Management', 'Incident Response', 'SIEM', 'Firewalls']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-13 days')),
        'expires_at' => date('Y-m-d', strtotime('+17 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 3,
        'title' => 'Office Manager',
        'company' => 'Smooth Operations Co.',
        'logo' => 'https://ui-avatars.com/api/?name=SO&background=7C2D12&color=fff&size=128',
        'location' => 'Austin',
        'job_type' => 'Full-time',
        'salary' => '$55,000 - $70,000',
        'description' => 'Oversee daily office operations, manage supplies, coordinate vendors, support staff, and ensure a productive work environment. Strong organizational skills.',
        'skills' => json_encode(['Office Management', 'Administration', 'Vendor Management', 'Organization', 'Communication', 'Microsoft Office']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-21 days')),
        'expires_at' => date('Y-m-d', strtotime('+9 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 2,
        'title' => 'Full Stack Developer (PHP/Laravel)',
        'company' => 'Web Artisans',
        'logo' => 'https://ui-avatars.com/api/?name=WA&background=5B21B6&color=fff&size=128',
        'location' => 'Remote',
        'job_type' => 'Full-time',
        'salary' => '$90,000 - $120,000',
        'description' => 'Develop and maintain web applications using PHP, Laravel, and Vue.js/React. Experience with MySQL and REST APIs required.',
        'skills' => json_encode(['PHP', 'Laravel', 'MySQL', 'JavaScript', 'Vue.js', 'React', 'Full Stack Development', 'API Development']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'expires_at' => date('Y-m-d', strtotime('+29 days')),
        'is_active' => 1,
    ],
    [
        'user_id' => 1,
        'title' => 'Biomedical Engineer',
        'company' => 'MedTech Innovations',
        'logo' => 'https://ui-avatars.com/api/?name=MI&background=1E40AF&color=fff&size=128',
        'location' => 'Boston',
        'job_type' => 'Full-time',
        'salary' => '$85,000 - $110,000',
        'description' => 'Design, develop, and test medical devices and equipment. Knowledge of FDA regulations and experience with CAD software (SolidWorks) preferred.',
        'skills' => json_encode(['Biomedical Engineering', 'Medical Devices', 'Design Controls', 'FDA Regulations', 'CAD', 'SolidWorks', 'Testing']),
        'created_at' => date('Y-m-d H:i:s', strtotime('-24 days')),
        'expires_at' => date('Y-m-d', strtotime('+6 days')),
        'is_active' => 1,
    ],
];

// You can add functions here to interact with this data if needed,
// or simply include this file where the $sampleJobs array is required.

?>